### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by jogibear9988**
run tsc on "prepare"
so you could install the package via git URL and it will be compiled
see: https://docs.npmjs.com/cli/v7/using-npm/scripts#life-cycle-scripts

### CODE REVIEW

**Comment by AlCalzone** [comment]
I'm not a huge fan of compiling TypeScript during a package installation. TS often has breaking changes in minor updates (they don't do semver) and just pulling in a newer version of TS (e.g. `4.3.x` which satisfies `^4.2.0`) could break the installation.

If it is necessary to install from git, I prefer checking in the compiled JS files.

**Comment by jogibear9988** [comment]
I forgot that it would also compile when using the npm package.
This would then not work. The source is not in the package, I removed it via .npmignore
So maybe we'll revert. Is there no script wich is used only when installing via git?

**Comment by AlCalzone** [comment]
No, I'm not talking about the npm package - that seems fine.

**Comment by AlCalzone** [comment]
But if you install this from git, it will install `devDependencies` and compile TypeScript. That can cause a situation where the code won't build because you developed it with 4.2 for example, but 4.3 gets installed.

Should be no problem though to limit the TS version with `~` instead of `^` to make sure.

**Comment by jogibear9988** [comment]
okay, I also read again the script definition, so it should work.
Sure we could fix the TS version.
But the lockfile is in the repo, so it should use the correct tsc version.

**Comment by AlCalzone** [comment]
Lockfiles from dependencies are not respected AFAIK. They are used within a project to install the same dependency tree as before when you just run `npm install`. Installing a new version of a dependency will change the lockfile.

**Comment by jogibear9988** [comment]
Okay. When I think of it, how should it respect lockfiles of dependencys?
But what's the correct solution? To commit also the compiled files to the repo? I also don't like this

**Comment by AlCalzone** [comment]
Then I guess change the `typescript` devDependency from `^...` to `~...`

**Comment by jogibear9988** [comment]
are you sure that this is a problem?
I now installed the package, and non of it's dev dependencies is installed to my node_modules dir, but the library is compiled (so I think npm has installed them and removed after running prepare?)
If so, I think npm will also use the correct typescript version.... But I don't know

**Comment by jogibear9988** [comment]
I did not find any info about this, and how this works

**Comment by Apollon77** [comment]
Should we simply resetversion to 0.0.1 and do a release and test it out?

**Comment by AlCalzone** [comment]
> I think npm will also use the correct typescript version

I'm not saying this is a problem **now** - but it can happen. Using ~ instead of ^ just makes sure that we don't get suprised in the future when TS introduces a breaking change that affects us.

**Pull request merged**
